meta_title: "CoursMaPoule : Courrez et rencontrez vos collègues "
meta_description: "Ne courrez plus jamais seul et rencontrer vos collègues."
meta_image: "app/assets/images/chicken-avatar-dark.jpg" # Une image dans votre dossier app/assets/images/
