meta_title: "CoursMaPoule : Courez et rencontrez vos collègues "
meta_description: "Profitez de vos pauses déjeuner pour courir avec vos collègues."
meta_image: "interval.jpg" # Une image dans votre dossier app/assets/images/
