meta_title: "CoursMaPoule : Courez et rencontrez vos collègues "
meta_description: "Ne courez plus jamais seul et rencontrez vos collègues."
meta_image: "funrunners-girls.jpg" # Une image dans votre dossier app/assets/images/
