meta_title: "CoursMaPoule : Courrez et rencontrez vos collègues "
meta_description: "Ne courrez plus jamais seul et rencontrez vos collègues."
meta_image: "funrunners-girls.jpg" # Une image dans votre dossier app/assets/images/
